apiVersion: apps/v1
kind: Deployment
metadata:
  name: antaeus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antaeus
  template:
    metadata:
      labels:
        app: antaeus
    spec:
      containers:
      - name: antaeus
        image: mousazeidbaker/pleo-antaeus:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: PAYMENT_PROVIDER_ENDPOINT
          value: http://payment.default/v1/payments
        readinessProbe:
          httpGet:
            path: /rest/health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /rest/health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /rest/health
            port: 8000
          failureThreshold: 60
          periodSeconds: 10
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
