name: Publish Docker image

on:
  push:
    branches:
      - 'master'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Antaeus
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mousazeidbaker/pleo-antaeus:latest

      - name: Build & Push Payment
        uses: docker/build-push-action@v2
        with:
          context: payment
          push: true
          tags: mousazeidbaker/pleo-payment:latest
